spring.application.name=BffBancoWeb
server.port=8081

# Configuracion de base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/backend_3
spring.datasource.username=myuser
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=always
spring.sql.init.platform=mysql

spring.batch.jdbc.initialize-schema=always

# JWT
jwt.secret=Clave-secreta-Bff-Web-F4hJ1cG0sZ8eN4wM7uO9iT2aB5kL3dP6jH8rX1vC4fE
jwt.expiration=18000000

# JWT de servicio (compartido con microservicio de Banco)
jwt.service-secret=Clave-secreta-Bff-Servicio-F4hJ1cG0sZ8eN4wM7uO9iT2aB5kL3dP6jH8rX1
jwt.service-expiration=18000000