DROP TABLE IF EXISTS tarjetas;

CREATE TABLE tarjetas (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    numero CHAR(16) NOT NULL,
    pin VARCHAR(255) NOT NULL,
    rol VARCHAR(20) NOT NULL DEFAULT 'CLIENTE'
);